apiVersion: v2
name: volsync
type: application
description: Asynchronous data replication for Kubernetes
home: https://volsync.readthedocs.io/
icon: https://raw.githubusercontent.com/backube/volsync/main/docs/media/volsync.svg?sanitize=true
sources:
  - https://github.com/backube/volsync
maintainers:
  - name: John Strunk
    email: jstrunk@redhat.com
    url: https://github.com/JohnStrunk
  - name: Tesshu Flower
    email: tflower@redhat.com
    url: https://github.com/tesshuflower
keywords:
  - backup
  - csi
  - data
  - disaster recovery
  - replication
  - storage
annotations:  # https://artifacthub.io/docs/topics/annotations/helm/
  # Changelog for current chart & app version
  # Kinds: added, changed, deprecated, removed, fixed, and security
  artifacthub.io/changes: |
    - kind: added
      description: New rsync-tls mover that uses stunnel instead of sshd for rsync traffic
    - kind: added
      description: moverServiceAccount parameter in the spec for advanced users
    - kind: changed
      description: All movers except rsync-ssh run as a normal user (see docs)
    - kind: changed
      description: VolSync now uses a single container image for the controller and all movers
    - kind: changed
      description: Rclone upgraded to v1.61.1
    - kind: changed
      description: Restic upgraded to 0.15.1
    - kind: changed
      description: Syncthing upgraded to v1.23.1
    - kind: fixed
      description: Syncthing should ignore lost+found directory
    - kind: security
      description: kube-rbac-proxy upgraded to 0.14.0
  artifacthub.io/crds: |
    - kind: ReplicationDestination
      version: v1alpha1
      name: replicationdestination.volsync.backube
      displayName: Replication destination
      description: Defines the destination of a replicated volume
    - kind: ReplicationSource
      version: v1alpha1
      name: replicationsource.volsync.backube
      displayName: Replication source
      description: Defines the source of a replicated volume
  artifacthub.io/license: AGPL-3.0-or-later
  artifacthub.io/operator: "true"
  artifacthub.io/operatorCapabilities: Basic Install
  artifacthub.io/signKey: |
    fingerprint: 2C937ADACD4BEF921197F66EDC7556B1903A252B
    url: https://keys.openpgp.org/vks/v1/by-fingerprint/2C937ADACD4BEF921197F66EDC7556B1903A252B

# We require v1 CSI snapshots (1.20+)
# Adding "-0" at the end of the version string permits pre-release kube versions
# to match. See https://github.com/helm/helm/issues/6190
kubeVersion: "^1.20.0-0"

# This is the chart version. This version number should be incremented each time
# you make changes to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: "0.7.2"

# This is the version number of the application being deployed. This version
# number should be incremented each time you make changes to the application.
# Versions are not expected to follow Semantic Versioning. They should reflect
# the version the application is using. It is recommended to use it with quotes.
appVersion: "0.7.2"
