# permissions for end users to view replicationsources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: replicationsource-viewer-role
rules:
- apiGroups:
  - scribe.backube
  resources:
  - replicationsources
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - scribe.backube
  resources:
  - replicationsources/status
  verbs:
  - get
