# permissions for end users to edit sources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: source-editor-role
rules:
- apiGroups:
  - scribe.backube
  resources:
  - sources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scribe.backube
  resources:
  - sources/status
  verbs:
  - get
