{{- if not .Values.metrics.disableAuth }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "volsync.fullname" . }}-metrics-auth-rolebinding
  labels:
    {{- include "volsync.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "volsync.fullname" . }}-metrics-auth-role
subjects:
- kind: ServiceAccount
  name: {{ include "volsync.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
