apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "scribe.fullname" . }}-proxy
  labels:
    {{- include "scribe.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "scribe.fullname" . }}-proxy
subjects:
- kind: ServiceAccount
  name: {{ include "scribe.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
