apiVersion: scorecard.operatorframework.io/v1alpha3
kind: Configuration
metadata:
  name: config
serviceaccount: volsync-test-runner
stages:
- parallel: false
  tests:
  - entrypoint:
    - volsync-custom-scorecard-tests
    - deploy-prereqs
    image: quay.io/backube/volsync-custom-scorecard-tests:latest
    labels:
      suite: volsync-e2e
      test: deploy-prereqs
- parallel: true
  tests:
  - entrypoint:
    - volsync-custom-scorecard-tests
    - test_mem_usage.yml
    image: quay.io/backube/volsync-custom-scorecard-tests:latest
    labels:
      suite: volsync-e2e
      test: test_mem_usage.yml
    storage:
      spec:
        mountPath: {}
  - entrypoint:
    - volsync-custom-scorecard-tests
    - test_multi_sync_snapshot_rclone.yml
    image: quay.io/backube/volsync-custom-scorecard-tests:latest
    labels:
      suite: volsync-e2e
      test: test_multi_sync_snapshot_rclone.yml
    storage:
      spec:
        mountPath: {}
  - entrypoint:
    - volsync-custom-scorecard-tests
    - test_multi_sync_snapshot_rsync.yml
    image: quay.io/backube/volsync-custom-scorecard-tests:latest
    labels:
      suite: volsync-e2e
      test: test_multi_sync_snapshot_rsync.yml
    storage:
      spec:
        mountPath: {}
  - entrypoint:
    - volsync-custom-scorecard-tests
    - test_namespace_role.yml
    image: quay.io/backube/volsync-custom-scorecard-tests:latest
    labels:
      suite: volsync-e2e
      test: test_namespace_role.yml
    storage:
      spec:
        mountPath: {}
  - entrypoint:
    - volsync-custom-scorecard-tests
    - test_rclone_normal.yml
    image: quay.io/backube/volsync-custom-scorecard-tests:latest
    labels:
      suite: volsync-e2e
      test: test_rclone_normal.yml
    storage:
      spec:
        mountPath: {}
  - entrypoint:
    - volsync-custom-scorecard-tests
    - test_rclone_priv.yml
    image: quay.io/backube/volsync-custom-scorecard-tests:latest
    labels:
      suite: volsync-e2e
      test: test_rclone_priv.yml
    storage:
      spec:
        mountPath: {}
  - entrypoint:
    - volsync-custom-scorecard-tests
    - test_rclone_with_customca_configmap.yml
    image: quay.io/backube/volsync-custom-scorecard-tests:latest
    labels:
      suite: volsync-e2e
      test: test_rclone_with_customca_configmap.yml
    storage:
      spec:
        mountPath: {}
  - entrypoint:
    - volsync-custom-scorecard-tests
    - test_rclone_with_customca_secret.yml
    image: quay.io/backube/volsync-custom-scorecard-tests:latest
    labels:
      suite: volsync-e2e
      test: test_rclone_with_customca_secret.yml
    storage:
      spec:
        mountPath: {}
  - entrypoint:
    - volsync-custom-scorecard-tests
    - test_replication_sched_snap.yml
    image: quay.io/backube/volsync-custom-scorecard-tests:latest
    labels:
      suite: volsync-e2e
      test: test_replication_sched_snap.yml
    storage:
      spec:
        mountPath: {}
  - entrypoint:
    - volsync-custom-scorecard-tests
    - test_replication_sync_direct.yml
    image: quay.io/backube/volsync-custom-scorecard-tests:latest
    labels:
      suite: volsync-e2e
      test: test_replication_sync_direct.yml
    storage:
      spec:
        mountPath: {}
  - entrypoint:
    - volsync-custom-scorecard-tests
    - test_restic_manual_normal.yml
    image: quay.io/backube/volsync-custom-scorecard-tests:latest
    labels:
      suite: volsync-e2e
      test: test_restic_manual_normal.yml
    storage:
      spec:
        mountPath: {}
  - entrypoint:
    - volsync-custom-scorecard-tests
    - test_restic_manual_priv.yml
    image: quay.io/backube/volsync-custom-scorecard-tests:latest
    labels:
      suite: volsync-e2e
      test: test_restic_manual_priv.yml
    storage:
      spec:
        mountPath: {}
  - entrypoint:
    - volsync-custom-scorecard-tests
    - test_restic_with_customca_configmap.yml
    image: quay.io/backube/volsync-custom-scorecard-tests:latest
    labels:
      suite: volsync-e2e
      test: test_restic_with_customca_configmap.yml
    storage:
      spec:
        mountPath: {}
  - entrypoint:
    - volsync-custom-scorecard-tests
    - test_restic_with_customca_secret.yml
    image: quay.io/backube/volsync-custom-scorecard-tests:latest
    labels:
      suite: volsync-e2e
      test: test_restic_with_customca_secret.yml
    storage:
      spec:
        mountPath: {}
  - entrypoint:
    - volsync-custom-scorecard-tests
    - test_restic_with_previous.yml
    image: quay.io/backube/volsync-custom-scorecard-tests:latest
    labels:
      suite: volsync-e2e
      test: test_restic_with_previous.yml
    storage:
      spec:
        mountPath: {}
  - entrypoint:
    - volsync-custom-scorecard-tests
    - test_restic_with_restoreasof.yml
    image: quay.io/backube/volsync-custom-scorecard-tests:latest
    labels:
      suite: volsync-e2e
      test: test_restic_with_restoreasof.yml
    storage:
      spec:
        mountPath: {}
  - entrypoint:
    - volsync-custom-scorecard-tests
    - test_restic_without_trigger.yml
    image: quay.io/backube/volsync-custom-scorecard-tests:latest
    labels:
      suite: volsync-e2e
      test: test_restic_without_trigger.yml
    storage:
      spec:
        mountPath: {}
  - entrypoint:
    - volsync-custom-scorecard-tests
    - test_roles.yml
    image: quay.io/backube/volsync-custom-scorecard-tests:latest
    labels:
      suite: volsync-e2e
      test: test_roles.yml
    storage:
      spec:
        mountPath: {}
  - entrypoint:
    - volsync-custom-scorecard-tests
    - test_roles_privileged.yml
    image: quay.io/backube/volsync-custom-scorecard-tests:latest
    labels:
      suite: volsync-e2e
      test: test_roles_privileged.yml
    storage:
      spec:
        mountPath: {}
  - entrypoint:
    - volsync-custom-scorecard-tests
    - test_rsync_tls_normal.yml
    image: quay.io/backube/volsync-custom-scorecard-tests:latest
    labels:
      suite: volsync-e2e
      test: test_rsync_tls_normal.yml
    storage:
      spec:
        mountPath: {}
  - entrypoint:
    - volsync-custom-scorecard-tests
    - test_rsync_tls_normal_diskrsync.yml
    image: quay.io/backube/volsync-custom-scorecard-tests:latest
    labels:
      suite: volsync-e2e
      test: test_rsync_tls_normal_diskrsync.yml
    storage:
      spec:
        mountPath: {}
  - entrypoint:
    - volsync-custom-scorecard-tests
    - test_rsync_tls_priv.yml
    image: quay.io/backube/volsync-custom-scorecard-tests:latest
    labels:
      suite: volsync-e2e
      test: test_rsync_tls_priv.yml
    storage:
      spec:
        mountPath: {}
  - entrypoint:
    - volsync-custom-scorecard-tests
    - test_rsync_tls_priv_diskrsync.yml
    image: quay.io/backube/volsync-custom-scorecard-tests:latest
    labels:
      suite: volsync-e2e
      test: test_rsync_tls_priv_diskrsync.yml
    storage:
      spec:
        mountPath: {}
  - entrypoint:
    - volsync-custom-scorecard-tests
    - test_simple_rsync.yml
    image: quay.io/backube/volsync-custom-scorecard-tests:latest
    labels:
      suite: volsync-e2e
      test: test_simple_rsync.yml
    storage:
      spec:
        mountPath: {}
  - entrypoint:
    - volsync-custom-scorecard-tests
    - test_simple_rsync_diskrsync.yml
    image: quay.io/backube/volsync-custom-scorecard-tests:latest
    labels:
      suite: volsync-e2e
      test: test_simple_rsync_diskrsync.yml
    storage:
      spec:
        mountPath: {}
  - entrypoint:
    - volsync-custom-scorecard-tests
    - test_syncthing_cluster_sync_normal.yml
    image: quay.io/backube/volsync-custom-scorecard-tests:latest
    labels:
      suite: volsync-e2e
      test: test_syncthing_cluster_sync_normal.yml
    storage:
      spec:
        mountPath: {}
  - entrypoint:
    - volsync-custom-scorecard-tests
    - test_syncthing_cluster_sync_priv.yml
    image: quay.io/backube/volsync-custom-scorecard-tests:latest
    labels:
      suite: volsync-e2e
      test: test_syncthing_cluster_sync_priv.yml
    storage:
      spec:
        mountPath: {}
  - entrypoint:
    - volsync-custom-scorecard-tests
    - test_volumepopulator.yml
    image: quay.io/backube/volsync-custom-scorecard-tests:latest
    labels:
      suite: volsync-e2e
      test: test_volumepopulator.yml
    storage:
      spec:
        mountPath: {}
storage:
  spec:
    mountPath: {}
